/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Land: (() => {
      const name = "Land";
      return defineComponent(
        world,
        {
          owner: RecsType.Number,
          building: RecsType.Number,
          level: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    GlobalConfig: (() => {
      const name = "GlobalConfig";
      return defineComponent(
        world,
        {
          MAX_MAP_X: RecsType.Number,
          MAX_MAP_Y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    WarriorConfig: (() => {
      const name = "WarriorConfig";
      return defineComponent(
        world,
        {
          Train_Food: RecsType.Number,
          Train_Gold: RecsType.Number,
          Train_Iron: RecsType.Number,
          Train_Time: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          nick_name: RecsType.Number,
          joined_time: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Food: (() => {
      const name = "Food";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Iron: (() => {
      const name = "Iron";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Gold: (() => {
      const name = "Gold";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Warrior: (() => {
      const name = "Warrior";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Base: (() => {
      const name = "Base";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    LandCost: (() => {
      const name = "LandCost";
      return defineComponent(
        world,
        {
          cost_gold: RecsType.Number,
          cost_food: RecsType.Number,
          cost_iron: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    ETH: (() => {
      const name = "ETH";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Troop: (() => {
      const name = "Troop";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Training: (() => {
      const name = "Training";
      return defineComponent(
        world,
        {
          start_time: RecsType.Number,
          total: RecsType.Number,
          out: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    UserWarrior: (() => {
      const name = "UserWarrior";
      return defineComponent(
        world,
        {
          balance: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
